### ISSUE TITLE
Basic Support of query and path parameters

### ISSUE THREAD

**Issue by adamyork** [radAdam/wiremock-velocity-transformer#3]
The VelocityContext should be aware of request path and query parameters.

**Comment by nicechester** [comment]
My implementation is at https://github.com/nicechester/wiremock-velocity-transformer/pull/1
You may refer to my wiki page - https://github.com/nicechester/wiremock-velocity-transformer/wiki

**Comment by adamyork** [comment]
@nicechester https://github.com/adamyork/wiremock-velocity-transformer/pull/4. This should give you a basic level of support for query parameters and request bodies. The implementation is not exactly matching your original. I opted for a more agnostic , naive approach. Note I have not released 1.5 version to maven central. Ill need to do that this weekend. Cheers.
