### ISSUE TITLE
Not able to see velocity working

### ISSUE THREAD

**Issue by alexanderm2018** [radAdam/wiremock-velocity-transformer#5]
In your example you provided the json representation of response but not mapping file.
so I added my mapping file but have not observed response was using the template.
Here console out put when call mapping to use your velocity. I have your jar in the same location where wiremock and started it with the command you have provided.
![image](https://user-images.githubusercontent.com/36869564/41869456-e89e40b8-786d-11e8-8bb0-f1e73477886d.png)

**Comment by alexanderm2018** [comment]
Sorry it was my bad since I have created response body with extension json not vm, after changing the extension to .vm things seems working fine.

![image](https://user-images.githubusercontent.com/36869564/41870054-bda85fea-786f-11e8-8dca-90e2e381f06b.png)

**Comment by adamyork** [comment]
Okay glad you found the issue.  I included a functional directory with examples in the root of the repository. https://github.com/adamyork/wiremock-velocity-transformer/tree/master/functional/mappings.

**Comment by alexanderm2018** [comment]
yes this is where I found the clue, nice useful stuff you done.
