### ISSUE TITLE
Wiremock fails if mappings with content body exist

### ISSUE THREAD

**Issue by PieterVanEde** [radAdam/wiremock-velocity-transformer#7]
In version 2.0 of this bridge (thanks a lot for it) our Wiremock breaks because our projects also contains mappins that specify a content-body instead of a bodyFilename.

In version 1.5 this still works, and I have found the cause to be 2 booleans switched places in the refactoring between 1.5 and 2.0. I will file a PR shortly.

**Comment by PieterVanEde** [comment]
I have just created PR GH-8 to fix this.

**Comment by adamyork** [comment]
Sure will fix.

**Comment by adamyork** [comment]
Okay I have merged your changes into HEAD and tested. Published new standalone release, https://github.com/adamyork/wiremock-velocity-transformer/releases/tag/2.1-release. I have not yet published the artifact to maven central. That will take a bit of a time. Hope this moves you forward. Thanks for the contribution.

**Comment by PieterVanEde** [comment]
Thanks for the quick reaction! Much appreciated!
